# Generated by Django 3.2 on 2023-10-21 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=125, null=True)),
                ('longitude', models.CharField(blank=True, max_length=125, null=True)),
                ('is_driver_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.driverlocation'),
        ),
    ]
