# Generated by Django 3.2 on 2023-10-21 15:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231021_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='driverlocation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='user',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.driverlocation'),
        ),
    ]
